apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.pv.name}}
spec:
  capacity:
    storage: {{.Values.pv.storage}}
  accessModes:
  - {{.Values.pv.mode}}
  hostPath:
    path: "{{.Values.pv.path}}"
  persistentVolumeReclaimPolicy: Retain
